CREATE TABLE
STATION ( 
STATION_ID VARCHAR(4) not null,
STATION_NAME VARCHAR(255) not null,
REG_DTS DATE,
PRIMARY KEY(STATION_ID)
);

CREATE TABLE
MONTHLY_STATION ( 
MONTH INTEGER not null,
STATION_ID VARCHAR(4) not null,
MONTHLY_STATION_USER INTEGER,
REG_DTS DATE,
PRIMARY KEY(MONTH, STATION_ID),
FOREIGN KEY (STATION_ID) REFERENCES STATION(STATION_ID)
);

CREATE TABLE
MEMBER ( 
MEMBER_ID VARCHAR(30) not null,
MEMBER_PWD VARCHAR(2000) not null,
REG_DTS DATE,
PRIMARY KEY(MEMBER_ID)
);